#!/bin/bash
LOCAL_DIR=$(git rev-parse --show-toplevel)
cd $LOCAL_DIR

# Only staged and committed files should be tested
# Stash while testing, then pop
git stash -u --keep-index --include-untracked
grunt lint
git reset --hard
git stash pop --quiet --index

#Create README.md of the commit messages as a daily changelog
README="$LOCAL_DIR/README.md"
echo "CHANGELOG" > $README
echo ---------------------- >> $README
git log --no-merges --format="%cd" --date=short | sort -u -r | while read DATE ; do
	echo >> $README
	echo -e "####$DATE####" >> $README
	echo >> $README
	GIT_PAGER=cat git log --no-merges --format=" * %s (\`%an\`)" --since="$DATE 00:00:00" --until="$DATE 09:00:00" >> $README
	GIT_PAGER=cat git log --no-merges --format=" * __%s__ (\`%an\`)" --since="$DATE 09:00:01" --until="$DATE 17:30:00" >> $README
	GIT_PAGER=cat git log --no-merges --format=" * %s (\`%an\`)" --since="$DATE 17:30:01" --until="$DATE 24:00:00" >> $README
done
git add $README
