#!/bin/bash
LOCAL_DIR=$(git rev-parse --show-toplevel)
LOCAL_DIR=${LOCAL_DIR:-.}
cd $LOCAL_DIR

# Define tab character to get around sed limitation
TAB=$'\t'

# Require good linting to commit
# exit if task failed
if grunt lint; then

	# File References
	README="$LOCAL_DIR/README.md"
	CHANGELOG="$LOCAL_DIR/CHANGELOG.md"
	TODO="$LOCAL_DIR/TODO.md"
	SRC="$LOCAL_DIR/sjs/core"

	# Clear the contents from TO DO to the end of file and prepare for appending
	sed -i "" -e '/##\ TODO\ ##/,$ d' $README 2> /dev/null

	######## TO DO #########
	echo "## TODO ##" > $TODO
	find "${SRC}" -type f -exec grep -H 'TODO:' {} \; 2> /dev/null | grep -v -e TODO.md -e README.md -e pre-commit | awk '{for (i=1; i<=NF-1; i++) $i = $(i+1); NF-=1; print}' | sed -e "s/.*TODO:[ ${TAB}]*//" | sed -e "s/^/- /" >> $TODO 2> /dev/null
	echo "" >> $TODO

	######## CHANGELOG #########
	# Add a daily breakdown of commits to the project as a changelog to the CHANGELOG
	echo "## COMMIT LOG ##" > $CHANGELOG
	git log --no-merges --format="%cd" --date=short | sort -u -r | while read DATE ; do
		echo >> $CHANGELOG
		echo -e "####$DATE####" >> $CHANGELOG
		echo >> $CHANGELOG
		GIT_PAGER=cat git log --no-merges --format=" * %s (\`%an\`)" --since="$DATE 00:00:00" --until="$DATE 09:00:00" >> $CHANGELOG
		GIT_PAGER=cat git log --no-merges --format=" * __%s__ (\`%an\`)" --since="$DATE 09:00:01" --until="$DATE 17:30:00" >> $CHANGELOG
		GIT_PAGER=cat git log --no-merges --format=" * %s (\`%an\`)" --since="$DATE 17:30:01" --until="$DATE 24:00:00" >> $CHANGELOG
	done

	######## README ###########
	cat $TODO >> $README
	cat $CHANGELOG >> $README

	######## UPDATE GIT ###########
	git add $CHANGELOG
	git add $TODO
	git add $README

fi
